name: we_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # For using cupertino icons
  cupertino_icons: ^1.0.2
  
  # For integrating firebase
  firebase_core: ^2.2.0

  # For handling firebase authentication
  firebase_auth: ^4.1.3

  # For handling google sign in
  google_sign_in: ^5.4.2

  # For accessing cloud firestore database
  cloud_firestore: ^4.1.0

  # For showing network images
  cached_network_image: ^3.2.3

  # For picking images
  image_picker: ^0.8.6

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^11.0.6

  # For showing Emojis
  emoji_picker_flutter: ^1.5.1

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^14.2.0

  # For calling RestAPIs
  http: ^0.13.5

  # For creating notification channel
  flutter_notification_channel: ^2.0.0

  # For storing images into gallery
  gallery_saver: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: "^0.10.0"

# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/icon.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true
  

  # For recommended coding practices
  flutter_lints: ^2.0.0

flutter:

  # For enabling material design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
